spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:goldenRaspberryAwardsdbKotlin?createDatabaseIfNotExist=true
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
      globally_quoted_identifiers: true
      jdbc:
        batch_size: 4
      order_inserts: true
      ddl:
        auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
